version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "16:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.1
    - 3.4.3
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: tox
    versions:
    - 3.20.1
    - 3.21.3
  - dependency-name: pytest
    versions:
    - 6.2.1
  - dependency-name: scikit-learn
    versions:
    - 0.24.0
  - dependency-name: numpy
    versions:
    - 1.19.4
