name: py-wave-runup
channels:
- conda-forge
- defaults
dependencies:
- black <20.0,>=18.3
- codecov ==2.*,>=2.0.0
- coverage ==5.*,>=5.0.0
- joblib ==0.*,>=0.14.1
- numpy ==1.*,>=1.16.0
- pandas ==1.*,>=1.3.0
- pre-commit ==1.*,>=1.18.0
- pytest ==5.*,>=5.3.0
- pytest-cov ==2.*,>=2.8.0
- pytest-runner ==5.*,>=5.1.0
- scikit-learn ==0.*,>=0.24.0
- sphinx ==2.*,>=2.3.0
- sphinx-gallery ==0.*,>=0.5.0
- tox ==3.*,>=3.13.0
- tomlkit ==0.*,>=0.5.8
